[package]
name = "rust_etl"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["etl-core"]

[workspace.dependencies]
reqwest = { version = "0.12.28", features = ["json"] }
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
thiserror = "2.0.17"
async-trait = "0.1.89"
futures = "0.3.31"
arrow = { version = "57.1.0", features = ["json"] }

[dev-dependencies]
pretty_assertions = "1.4.1"


